---
# Debian related packages that must be installed on all systems

- name: apt-get dist-upgrade
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 43200 # invalid every 12 hours
    upgrade: dist


- name: install basic tools
  become: true
  apt: name={{ item }}
  with_items:
    - vim
    - rsync
    - git
    - zsh
